services:
  php:
    build:
      context: ./docker/php
      args:
        INSTALL_XDEBUG: true
    volumes:
      - ./quill:/var/www/quill
      - ./lab:/var/www/lab
    working_dir: /var/www/lab
    environment:
      - APP_ENV=local
    ports:
      - "9000:9000"

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./lab:/var/www/lab
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
